// Mocks generated by Mockito 5.4.6 from annotations
// in tv_shows_appp/test/shows_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_shows_appp/Features/model/cast_model.dart' as _i5;
import 'package:tv_shows_appp/Features/model/show_model.dart' as _i4;
import 'package:tv_shows_appp/Features/data/repositories/show_repository.dart'
    as _i2;
import 'package:tv_shows_appp/Features/presentation/view_model/show_view_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeShowRepository_0 extends _i1.SmartFake
    implements _i2.ShowRepository {
  _FakeShowRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ShowViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowViewModel extends _i1.Mock implements _i3.ShowViewModel {
  MockShowViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ShowRepository get showRepository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeShowRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ShowRepository);

  @override
  List<_i4.ShowModel> get shows =>
      (super.noSuchMethod(
            Invocation.getter(#shows),
            returnValue: <_i4.ShowModel>[],
          )
          as List<_i4.ShowModel>);

  @override
  List<_i5.CastModel> get cast =>
      (super.noSuchMethod(
            Invocation.getter(#cast),
            returnValue: <_i5.CastModel>[],
          )
          as List<_i5.CastModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isFetchingMore =>
      (super.noSuchMethod(
            Invocation.getter(#isFetchingMore),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasMore =>
      (super.noSuchMethod(Invocation.getter(#hasMore), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadShows() =>
      (super.noSuchMethod(
            Invocation.method(#loadShows, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadMore() =>
      (super.noSuchMethod(
            Invocation.method(#loadMore, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void search(String? query) => super.noSuchMethod(
    Invocation.method(#search, [query]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadCast(int? showId) =>
      (super.noSuchMethod(
            Invocation.method(#loadCast, [showId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
